# Configuration parameters for beaverdam

[database]
# Information about the database containing metadata
address = "localhost"
port = 27017
db_name = "testodml"
collection_name = "odmlmetadata"

[fields]
# The name you want to use to refer to each metadata field, and the location of the
# field in the database
Name = "Document.sections.session.sections.Session.properties.Name.value"
GivenName = "Document.sections.subject.sections.Subject.properties.GivenName.value"
ShortName = "Document.sections.session.sections.Session.sections.Task.properties.ShortName.value"
dtp_filename = "Document.sections.TaskParameters.properties.dtp_filename.value"
AverageTrialTime = "Document.sections.session.sections.Session.sections.Performance.properties.AverageTrialTime.value"
AverageErrorCount = "Document.sections.session.sections.Session.sections.Performance.properties.AverageErrorCount.value"
SortingAuthor1 = "Document.sections.SessionInfo.sections.spike_sorting1.properties.SortingAuthor.value"
SortingAuthor2 = "Document.sections.SessionInfo.sections.spike_sorting2.properties.SortingAuthor.value"
SortingAuthor3 = "Document.sections.SessionInfo.sections.spike_sorting3.properties.SortingAuthor.value"
SortingAuthor4 = "Document.sections.SessionInfo.sections.spike_sorting4.properties.SortingAuthor.value"
ElectrophysQuality = "Document.sections.session.sections.Session.sections.DataQuality.properties.Electrophysiology.value"
EyeQuality = "Document.sections.session.sections.Session.sections.DataQuality.properties.Eye.value"
HandQuality = "Document.sections.session.sections.Session.sections.DataQuality.properties.Hand.value"
Modality1 = "Document.sections.session.sections.Session.properties.Modality1.value"
Modality2 = "Document.sections.session.sections.Session.properties.Modality2.value"
Modality3 = "Document.sections.session.sections.Session.properties.Modality3.value"

[filters]
# Which fields you will be able to place conditions on to filter items.  These fields
# will each be turned into a set of checkboxes showing all available options for that
# field.
headings = [
    "GivenName",
    "ShortName",
]

[table]
# Which fields to show in the data table
columns = [
    "Name",
    "GivenName",
    "ShortName",
    "dtp_filename",
    "AverageTrialTime",
    "AverageErrorCount",
    "SortingAuthor1",
    "SortingAuthor2",
    "SortingAuthor3",
    "SortingAuthor4",
    "ElectrophysQuality",
    "EyeQuality",
    "HandQuality",
    "Modality1",
    "Modality2",
    "Modality3",
]

[plots]
# Which fields to plot, and how to plot them.  Each plot must have the following keys:
#   - data_field (string or list of strings): name of the field(s) to plot
#   - plot_type (string): type of plot ("pie", "bar", "scatter", "box")
monkey_name.data_field = "GivenName"
monkey_name.plot_type = "pie"

task_name.data_field = "ShortName"
task_name.plot_type = "bar"

errors_vs_time.data_field = ["AverageErrorCount", "AverageTrialTime"]
errors_vs_time.plot_type = "scatter"

errors_vs_monkey.data_field = ["AverageErrorCount", "GivenName"]
errors_vs_monkey.plot_type = "box"