# Configuration parameters for beaverdam

[raw_metadata]
# Information about the location and type of metadata files to include in the database.
# Only needed to build a database, not to run a user interface with an existing 
# database.
directory = '/home/more/Documents/Beaverdam/Odml/odml_r2g_all_2024-02-08'
file_type = '.odml'

[database]
# Information about the database containing metadata.  This is the database which will 
# be created, updated, or read from.
address = "localhost"
port = 27017
db_name = "testodml"
collection_name = "odmlmetadata_r2g"

[fields]
# The name you want to use to refer to each metadata field, and the location of the
# field in the database
SessionID = "_id"
GivenName = "Document.sections.Subject.properties.GivenName.value"
Date = "Document.sections.Recording.properties.Date.value"
Weekday = "Document.sections.Recording.properties.Weekday.value"
Time = "Document.sections.Recording.properties.Time.value"
Duration = "Document.sections.Recording.properties.Duration.value"
TaskType = "Document.sections.Recording.properties.TaskType.value"
TotalTrialCount = "Document.sections.Recording.sections.TaskSettings.properties.TotalTrialCount.value"
CorrectTrialCount = "Document.sections.Recording.sections.TaskSettings.properties.CorrectTrialCount.value"
GripErrorTrialCount = "Document.sections.Recording.sections.TaskSettings.properties.GripErrorTrialCount.value"
IsSpikeSorted = "Document.sections.Recording.properties.IsSpikeSorted.value"
TrialTypes = "Document.sections.Experiment.sections.Behavior.properties.TrialTypes.value"

[filters]
# Which fields you will be able to place conditions on to filter items.  These fields
# will each be turned into a set of checkboxes showing all available options for that
# field.
headings = [
    "GivenName",
    "TaskType",
    "IsSpikeSorted",
]

[table]
# Which fields to show in the data table
columns = [
    "GivenName",
    "Date",
    "Weekday",
    "Time",
    "Duration",
    "TaskType",
    "TotalTrialCount",
    "CorrectTrialCount",
    "GripErrorTrialCount",
    "IsSpikeSorted",
    "TrialTypes",
]

[plots]
# Which fields to plot, and how to plot them.  Each plot must have the following keys:
#   - data_field (string or list of strings): name of the field(s) to plot
#   - plot_type (string): type of plot ("pie", "bar", "scatter", "box")
monkey_name.data_field = "GivenName"
monkey_name.plot_type = "pie"

task_name.data_field = "TaskType"
task_name.plot_type = "bar"

errors_vs_monkey.data_field = ["GripErrorTrialCount", "Duration"]
errors_vs_monkey.plot_type = "scatter"

errors_vs_day.data_field = ["GripErrorTrialCount", "Weekday"]
errors_vs_day.plot_type = "box"