# NOTE: this repository uses the tool somesy to help you easily maintain
# and synchronize all the high-level project metadata across multiple files.
# To see which other metadata can be added, check out the somesy documentation
# https://materials-data-science-and-informatics.github.io/somesy/main/
[tool.somesy.project]
name = "beaverdam"
version = "0.1.0"
description = "Build, explore, and visualize experimental databases of metadata"
license = "BSD-3-Clause"

repository = "https://github.com/INM-6/beaverdam"
homepage = "https://github.com/INM-6/beaverdam"
documentation = "https://github.com/INM-6/beaverdam"

[[tool.somesy.project.people]]
given-names = "Heather"
family-names = "More"
email = "h.more@fz-juelich.de"
affiliation = "Institute for Advanced Simulation (IAS-6 and IAS-9), J端lich Research Centre, J端lich, Germany"
orcid = "http://orcid.org/0000-0002-7514-2199"
author = true
maintainer = true

[[tool.somesy.project.people]]
given-names = "Michael"
family-names = "Denker"
email = "m.denker@fz-juelich.de"
affiliation = "Institute for Advanced Simulation (IAS-6), J端lich Research Centre, J端lich, Germany"
orcid = "https://orcid.org/0000-0003-1255-7300"
author = true
maintainer = true

[tool.somesy.config]
verbose = true

[tool.poetry]
# ---- DO NOT EDIT - core project metadata managed by somesy  ----
# to update, edit values in [tool.somesy.project] section
# and run somesy: poetry run somesy
name = "beaverdam"
version = "0.1.0"
description = ""
authors = ["Heather More <hmore@sfu.ca>"]
license = "BSD-3-Clause"
# ----

include = [
    "LICENCE",
    "CITATION.cff",
    "codemeta.json",
]

packages = [{include = "beaverdam", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
pymongo = "^4.3.2"
dash = "^2.6.2"
dash-extensions = "^0.1.6"
pandas = ">=2.1.0"
tomli = "^2.0.1"
plotly = "^5.13.1"
dash-bootstrap-components = ">=1.5.0"
dash-trich-components = "^1.0.0"
dash-mantine-components = "^0.12.1"
dash-bootstrap-templates = "^1.1.1"
odML = "^1.5.4"
tqdm = "^4.66.1"
typer = "^0.12.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ruff = "^0.3.7"

[tool.poetry.scripts]
beaverdam = 'beaverdam.cli:app'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# Tool Configurations
# -------------------

[tool.ruff.lint]
extend-select = ["I", "D", "B", "S", "W"]
ignore = ["D203", "D213", "D407", "B008"]